services:
  db:
    image: mysql:8
    container_name: restaurant_user_db
    networks:
      - restaurant
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: restaurant_user
      MYSQL_PASSWORD: restaurant_user
      MYSQL_DATABASE: user
    ports:
      - 4001:3306
    expose:
      - 4001
    volumes:
      - user:/var/lib/mysql
    restart: on-failure

  app:
    build:
      context: ../../
      dockerfile: config/Dockerfile
    container_name: restaurant_user_app
    environment:
      APP_MODE: $APP_MODE
    ports:
      - 9001:80
    expose:
      - 9001
    networks:
      - restaurant
    depends_on:
      - db
    restart: on-failure
    command: "/app/server"

networks:
  restaurant:
    name: restaurant

volumes:
  user:
    name: restaurant_user
