server: 
  host: ""
  port: 9000

db:
  host: "restaurant_db"
  port: 3306
  name: "restaurant"
  user: "restaurant"
  pass: "restaurant"

hash:
  min_length: 6
  salt: "800k570reh45h5417"
  alphabet: "abcdefghijklmnopqrstuvwxyz1234567890"
